ALTER TABLE [s].[Salary]
ALTER COLUMN Comment VARCHAR(100) COLLATE Polish_CI_AS

ALTER TABLE [s].[Salary]
ALTER COLUMN Name VARCHAR(40) COLLATE Polish_CI_AS

ALTER TABLE [s].[Salary]
ALTER COLUMN Source VARCHAR(40) COLLATE Polish_CI_AS